[phases.setup]
nixPkgs = ["nodejs_18"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npx http-server dist -p $PORT -a 0.0.0.0 --cors -c-1 -S -P http://localhost:$PORT?"
